name: run one-thing on cmba
on:
  workflow_dispatch:
    inputs:
      message:
        description: message
        required: true
      key:
        description: task key
      title:
        description: task title
      url:
        description: task url

jobs:
  run:
    runs-on: [self-hosted, cmba]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: execute one-thing
        run: |
          npx one-thing "${{ github.event.inputs.message }}"
      - name: update dash snippet
        if: ${{ github.event.inputs.key != '' }}
        run: |
          sqlite3 "/Users/chitacan/Library/Application Support/Dash/library.dash" \
            "UPDATE snippets SET body = '${{ github.event.inputs.key }}' WHERE sid = 1"
