name: run one-thing on cmba
on:
  workflow_dispatch:
    inputs:
      message:
        description: message
        required: true
      key:
        description: task key
      title:
        description: task title
      url:
        description: task url

jobs:
  run:
    runs-on: [self-hosted, cmba]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: execute one-thing
        run: |
          npx one-thing "${{ github.event.inputs.message }}"
      - name: update dash snippets
        if: ${{ github.event.inputs.key != '' && github.event.inputs.title != '' && github.event.inputs.url != ''}}
        env:
          DASH_DB: "/Users/chitacan/Library/Application Support/Dash/library.dash"
        run: |
          sqlite3 "$DASH_DB" \
            "UPDATE snippets SET body = '${{ github.event.inputs.key }}' WHERE sid = 1"
          sqlite3 "$DASH_DB" \
            "UPDATE snippets SET body = '${{ github.event.inputs.title }}' WHERE sid = 2"
          sqlite3 "$DASH_DB" \
            "UPDATE snippets SET body = '${{ github.event.inputs.url }}' WHERE sid = 3"
